### ISSUE TITLE
Vimplug cannot find master branch

### ISSUE THREAD

**Issue by CKolkey** [ojroques/nvim-lspfuzzy#1]
Since you're using Main. 
![Screen Shot 2020-12-11 at 11 18 32](https://user-images.githubusercontent.com/7228095/101891652-9fff9500-3ba2-11eb-869e-5254fea60ebf.png)

Perhaps update the readme to this:
`Plug 'ojroques/nvim-lspfuzzy', { 'branch': 'main' }`

**Comment by ojroques** [comment]
Ah yes thank you.

**Comment by ojroques** [comment]
Btw it seems vim-plug does support non-master branch now: https://github.com/junegunn/vim-plug/pull/1007.
