### ISSUE TITLE
How to use fzf for lsp?

### ISSUE THREAD

**Issue by TornaxO7** [ojroques/nvim-lspfuzzy#10]
So this is in your README.md file:

![image](https://user-images.githubusercontent.com/50843046/116856515-8d423700-abfb-11eb-803d-b32c024c5d15.png)

But I don't really understand what I have to do in order to be able to use FZF for searching symbols or references. Could you help me please?

**Comment by ojroques** [comment]
So if you want to use FZF for everything related to LSP (symbols, references, definitions etc) you should just add this to your config:
```lua
require('lspfuzzy').setup {}
```
Nothing more to do.

If you want to enable FZF only for some LSP functions such as code actions and prevent all other functions to use FZF, you can specify them using the `method` option:
```lua
require('lspfuzzy').setup {
  methods = ['textDocument/codeAction']   -- no LSP functions will use FZF except codeAction
}
```

I hope that's clear.

**Comment by TornaxO7** [comment]
Yes, it works now, thank you!

**Comment by alexzanderr** [comment]
i have `methods` = `all` and i dont see any functions to find definition of preview references
```lua
require('lspfuzzy').setup {
  methods = 'all',         -- either 'all' or a list of LSP methods (see below)
  jump_one = true,         -- jump immediately if there is only one location
  callback = nil,          -- callback called after jumping to a location
  fzf_preview = {          -- arguments to the FZF '--preview-window' option
    'right:+{2}-/2'          -- preview on the right and centered on entry
  },
  fzf_action = {           -- FZF actions
    ['ctrl-t'] = 'tabedit',  -- go to location in a new tab
    ['ctrl-v'] = 'vsplit',   -- go to location in a vertical split
    ['ctrl-x'] = 'split',    -- go to location in a horizontal split
  },
  fzf_modifier = ':~:.',   -- format FZF entries, see |filename-modifiers|
  fzf_trim = true,         -- trim FZF entries
}
```
how do i actually call lsp functions for all of the methods? i dont see any example in your readme.

**Comment by ojroques** [comment]
Not sure I understood your issue correctly but if you want the plugin to be enabled for *all* LSP methods, you don't actually need to set anything (`all` is the default value of the `methods` option) so this should suffice:
```lua
require('lspfuzzy').setup {}
```

Does it solve your problem?

**Comment by alexzanderr** [comment]
if you say setting `all` is just like settings `require('lspfuzzy').setup {}` and there shouldnt be a problem, then why are you asking me to do the same thing?

**Comment by ojroques** [comment]
You don't have to do anything. The `methods` option is there is you want to enable the plugin *only* for some LSP methods, you can pass a list to it like so:
```lua
methods = {'textDocument/references', 'textDocument/documentSymbol'}
```

Otherwise if you want all LSP methods to use the plugin, which is the default, don't change anything just use:
```lua
require('lspfuzzy').setup {} 
```
