### ISSUE TITLE
Code action text missing sometimes (tsserver)

### ISSUE THREAD

**Issue by sQVe** [ojroques/nvim-lspfuzzy#16]
👋🏼 

I mainly use the `tsserver` LSP and I'm seeing two issues when triggering `codeAction` with this plugin:

- [lspfuzzy] json: cannot unmarshal number into Go struct field Diagnostic.context.diagnostics.code of t
ype string
![image](https://user-images.githubusercontent.com/2284724/123658811-591d7800-d832-11eb-8e8a-147847d3e8f9.png)
 
- Sometimes, maybe 1 out of 10, the text of the actions are missing. As soon as I input text and then remove it the text renders correctly. Do note that the count is correct though.
![image](https://user-images.githubusercontent.com/2284724/123659163-aef22000-d832-11eb-83fe-0e0174f384b9.png)

Thank you for an otherwise awesome plugin 🙏🏼 Just ping if you need further input/information.

**Comment by ojroques** [comment]
Hello,

For the first issue, could you try to perform the same code action without the plugin? Just to be sure the error comes from the plugin and not from your language server.

For the second issue I have no clue why would that happen but I'll take a look.

**Comment by sQVe** [comment]
@ojroques The first issue is there without this plugin too 👍🏼 

```text
RPC[Error] code_name = unknown, code = 0, message = "json: cannot unmarshal number into Go struct field Diagnostic.context.diag
nostics.code of type string"
```

**Comment by sQVe** [comment]
I managed to fix this. See https://github.com/neovim/neovim/issues/14925 for further info. Closing issue! 🎉
