### ISSUE TITLE
fzf doesn't scroll preview to actual position

### ISSUE THREAD

**Issue by astavonin** [ojroques/nvim-lspfuzzy#17]
**Issue:**

Open a file with active LSP and call `references`. FZF window with references will pop up, but when you change the selected reference, the preview window shows the file in its current position (0 line for a closed file or current cursor position for an open file).

**Expected behavior:**

FZF window will scroll to a line with the selected reference.

**Environment:**

LSP `clangd` and `pyls` (the issue is reproducable on both LSPs)
Ubuntu 20.04
NeoVim 0.6.0
`nvim-lspfuzzy` - latest
`fzf` and `fzf.vim` installed, latest version

**Comment by ojroques** [comment]
I personally use `pyls`, Ubuntu 20.04 and Neovim nightly and have never run into this issue.

Do you have [bat](https://github.com/sharkdp/bat) installed? Otherwise maybe try [this](https://github.com/ojroques/nvim-lspfuzzy#preview-does-not-scroll-to-the-selected-location).

**Comment by astavonin** [comment]
Yes, sure, bat is installed.

**Comment by ojroques** [comment]
Can you share your Neovim config ? Or at least the parts related to LSP / FZF / the plugin.

**Comment by astavonin** [comment]
I had just:

```vim
lua require('lspfuzzy').setup {}

Plug 'ojroques/nvim-lspfuzzy'
```

This is my full config, but already replaced `nvim-lspfuzzy` with `fzf_lsp` that's why it's in diff form

https://github.com/astavonin/configs/commit/b32e6c091d62bd2ab2c10e63d24aac4bd6f13799#diff-553fdc02bfc19357d03441ac4b6cd4fd423fe261abd391d2dc82d3d209e73644R255

**Comment by ojroques** [comment]
Looking at your config, replacing
```vim
let g:fzf_preview_window = ['up:50%']
```
with
```vim
let g:fzf_preview_window = ['up:50%:+{2}-/2']  "+{2}-/2 makes the preview centered
```
would likely solve your issue. But if `fzf_lsp` works for you feel free to keep it.
