### ISSUE TITLE
Upstream workspace/applyEdit signature change breaks lspfuzzy

### ISSUE THREAD

**Issue by arsham** [ojroques/nvim-lspfuzzy#20]
Possibly at [this](https://github.com/neovim/neovim/commit/23fe6dba138859c1c22850b9ce76219141f546a0) commit, the signature of the handler has changed and is breaking this plugin.

[This](https://github.com/ojroques/nvim-lspfuzzy/blob/6f2cfbd0dffdbf0c74db5a3f91e2e65c27af545f/lua/lspfuzzy.lua#L90) code might be indirectly affected by the signature change.

**Comment by ojroques** [comment]
Thank you for letting me now. I didn't want to break the plugin for people not using Neovim master so I've pushed a new branch `dev` where this issue should be fixed. Can you check it out and let me now if it works fine?

I've also updated the readme accordingly.

**Comment by arsham** [comment]
Thank you for the fix :+1: , it works well.

**Comment by ojroques** [comment]
I've updated `dev` so that it also works for Neovim == 0.5 and merged  it into `main`. I'll delete `dev` so be sure to check out `main`.

**Comment by arsham** [comment]
I'm afraid the new release broke the plugin again. The `has('nvim-0.5.1')` reports `1` on my build (see below).

I am building neovim with `pacman` on Arch linux at `7a0468e7addc8745d82` because another plugin is still in [process of the same fix](https://github.com/nvim-lua/completion-nvim/pull/400).

```bash
NVIM v0.6.0-dev+216-g7a0468e7a
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/lib/ccache/bin/cc -D_FORTIFY_SOURCE=2 -march=native -mtune=native -O2 -pipe -fstack-protector-strong -flto -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/arsham/tmp/pkg/neovim-git/src/build/config -I/home/arsham/tmp/pkg/neovim-git/src/neovim-git/src -I/usr/include -I/home/arsham/tmp/pkg/neovim-git/src/build/src/nvim/auto -I/home/arsham/tmp/pkg/neovim-git/src/build/include
Compiled by arsham

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by ojroques** [comment]
Well you happen to be in a detached commit after 0.5 but before nightly/main, and I assume very few people use Neovim at such specific commits.

I don't want to introduce complexity by handling these corner cases so hopefully you are able to update to nightly/master soon. 

In the meantime I've pushed a tag `old-handlers` for your convenience that you can use in your plugin manager instead of the full hash.
