### ISSUE TITLE
Actions in fzf broken on nvim nightly

### ISSUE THREAD

**Issue by sQVe** [ojroques/nvim-lspfuzzy#25]
👋🏼 

I just noted that I'm no longer getting the actions in `fzf` on the latest neovim nightly. It works on `0.5.1` but fails on latest nightly (`v0.6.0-dev+368-g9337fff8a`).

Gimme a ping if you need any further information.

**Comment by ojroques** [comment]
Yes it seems there were quite a lot of changes related to code actions in neovim lately ([#15818](https://github.com/neovim/neovim/pull/15818)). I will take a look as soon as I have time.

**Comment by ojroques** [comment]
In the meantime I've disabled the plugin for code actions in nvim 0.5.2+ so that you can still use code actions via the quickfix window.

**Comment by alehatsman** [comment]
hey, it is working fine on my machine :)

![image](https://user-images.githubusercontent.com/3405704/144427309-02802ffa-b100-4334-99c1-892976e23abf.png)

![image](https://user-images.githubusercontent.com/3405704/144427339-3dcac52e-98c6-4f8d-bf06-a1ba30b21796.png)
