### ISSUE TITLE
Feature request: Adding support for tab drop

### ISSUE THREAD

**Issue by yolo2h** [ojroques/nvim-lspfuzzy#26]
Hi,
I like your plugin, and it's very useful.
I found `fzf` can jump to the window/tab where the buffer is open(set `['ctrl-t'] = 'tab drop'`), can `nvim-lspfuzzy` do this?

**Comment by yolo2h** [comment]
I write some code like:

```lua
-------------------- FZF FUNCTIONS -------------------------
local function jump(entries)
  ...
  -- A FZF action was used
  if opts.fzf_action[key] then
    if opts.fzf_action[key] == 'tab drop' then
      for _, buf_info in ipairs(vim.fn.getbufinfo()) do
        local uri = vim.uri_from_bufnr(buf_info.bufnr)
        if uri == locations[1]['uri'] then
          cmd('tab drop ' .. buf_info.name)
          break
        end
      end
    else
      cmd(opts.fzf_action[key])
    end
  end
  ...
end
```
It's ugly but works fine for my, could you add option(like `callback`) allow me rewrite that function?

**Comment by ojroques** [comment]
`tab drop` should work now in the latest commit (with `['ctrl-t'] = 'tab drop'`). Can you try and report if it works ?

**Comment by yolo2h** [comment]
Thank you so much, it works great!
