### ISSUE TITLE
call lua function in action

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ojroques/nvim-lspfuzzy#27]
hey, I have a setup using `fzf.vim` and `nvim-lspfuzzy`, with a custom function to send fzf selections to q qflist. 

``` lua
qf_populate = function(lines, mode)
    if mode == nil then
        lines = core.foreach(lines, function(item) return { filename = item, lnum = 1, col = 1 } end)
        mode = "r"
    end

    vim.fn.setqflist(lines, mode)
    vim.cmd [[
        copen
        setlocal statusline=%!v:lua.StatusLine('QuickFix')
        setlocal nobuflisted
        wincmd p
        echo hello
    ]]
end
```

and my `fzf_actions` is set as:
``` lua
vim.g.fzf_action = {
    ["ctrl-q"] = qf_populate,
    ["ctrl-x"] = "split",
    ["ctrl-v"] = "vsplit"
}
```

this setup works for `fzf.vim`, and a few custom LSP handlers I wrote (using qf_populate for multi-file refactors).  How can I get `lspfuzzy` to call this function, with the first param as the lines. ?

**Comment by ojroques** [comment]
Hello,

If you use <tab> to select multiple entries with `lspfuzzy`, then select one entry with <CR>, the plugin jumps to the selected entry and put the remaining entries into the quicklist. Does that suit the workflow you're requesting?

**Comment by ViRu-ThE-ViRuS** [comment]
Yes its the functionality i want, but i want to set the statusline and also want the ability to extend it . Is it possible to call the lua function? Fzf.vim is able to.

**Comment by ojroques** [comment]
It should work like you want in the latest commit. Can you try and tell me if it does?

**Comment by ViRu-ThE-ViRuS** [comment]
@ojroques yes it is perfect! I really appreciate you responding and reacting so quickly on this amazing project, it just shows the commitment, and effort you have put into making so many of our developer experiences better! Thank you :)

**Comment by ViRu-ThE-ViRuS** [comment]
okay I am noticing that even after calling the action function, it automatically sets the qflist and opens that split, which defeats the purpose of my qf_list function. I we can let action take complete control over what happens with the selections, which makes it more like the last callback. 

I suggest letting the function return calling functional action. What do you think?
