### ISSUE TITLE
let functional actions be the last callbacks to be called with selected items

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ojroques/nvim-lspfuzzy#28]
okay I am noticing that if we use a action which is a lua function, `lspfuzzy` will automatically set the `qflist` and open qflist, which might defeat the purpose fo the `action` argument. We can let `action` take complete control over what happens with the selections, which makes it more like the last callback.

I suggest letting the call `return` after calling functional action. 

builds on #27

**Comment by ojroques** [comment]
Done, let me know if it doesn't work as expected.

**Comment by ViRu-ThE-ViRuS** [comment]
perfect! Thanks!
