### ISSUE TITLE
No error message shown in :LspDiagnostics command

### ISSUE THREAD

**Issue by wustho** [ojroques/nvim-lspfuzzy#36]
![Screenshot_20220915_135000](https://user-images.githubusercontent.com/43810055/190334591-8602b86f-166d-4d42-8b85-8cbdc006d2b0.png)

Is it possible to show error msg?
eg. `coba.py:3:7 :Error : Name "asfasfd" is not defined`

**Comment by ojroques** [comment]
Done in latest commit :)
