### ISSUE TITLE
Feature Request: Severity color in LspDiagnostics

### ISSUE THREAD

**Issue by wustho** [ojroques/nvim-lspfuzzy#37]
Hey there, first of all thanks for this: https://github.com/ojroques/nvim-lspfuzzy/issues/36

I just wanna ask if it's possible to get color for the severity text. It doesn't need to set it according Diagnostic highlight, but maybe common diagnostic color. eg.
path/to/file: **ansi.red** [ERROR] **ansi.reset** error message bla bla

This would increase clarity.

**Comment by ojroques** [comment]
Good idea. I've added this feature in the latest commit.

**Comment by wustho** [comment]
Just synced, works well, thanks appreciated it
