### ISSUE TITLE
'textDocument/codeAction' not support?

### ISSUE THREAD

**Issue by linrongbin16** [ojroques/nvim-lspfuzzy#38]
Hi, in README, the supported LSP functions are:

callHierarchy/incomingCalls
callHierarchy/outgoingCalls
textDocument/declaration
textDocument/definition
textDocument/documentSymbol
textDocument/implementation
textDocument/references
textDocument/typeDefinition
workspace/symbol

So textDocument/codeAction not support?

**Comment by ojroques** [comment]
No it doesn't sorry. Implementing support for Code Actions is not trivial as the other methods unfortunately. See also [this issue](https://github.com/ojroques/nvim-lspfuzzy/issues/35) for why I chose not to support them and alternatives.
