### ISSUE TITLE
fzf preview not works

### ISSUE THREAD

**Issue by zanglg** [ojroques/nvim-lspfuzzy#4]
preview works well on fzf's built-in function, what debug info do you need to help

**Comment by wgurecky** [comment]
I also encountered this issue.  I think it has to do with :
https://github.com/ojroques/nvim-lspfuzzy/blob/7896597f54e0f7b90acda26468f5bbe97544b330/lua/lspfuzzy.lua#L82-L87

could try `let g:loaded_fzf_vim = 1`  in init.vim as a workaround.

**Comment by ojroques** [comment]
Hello!
Yes I've very recently (yesterday) changed how fzf.vim is detected because fzf.vim has just added the global variable g:loaded_fzf_vim` see https://github.com/junegunn/fzf.vim/commit/636a62f140181f80c8e7460a76ae6a5d2c5d97b2. So make sure to update fzf.vim and it should work.

**Comment by zanglg** [comment]
@wgurecky @ojroques 
let g:loaded_fzf_vim = 1 or update fzf.vim both works, thanks, closed.
