### ISSUE TITLE
Error when try to sink the fzf-result to quickfix window: set_qlist(a nil val)

### ISSUE THREAD

**Issue by huawenyu** [ojroques/nvim-lspfuzzy#40]
5     fix set_qlist(a nil val)
  6
  7 diff --git a/lua/lspfuzzy.lua b/lua/lspfuzzy.lua
  8 index fac5c6c..76a8937 100644
  9 --- a/lua/lspfuzzy.lua
 10 +++ b/lua/lspfuzzy.lua
 11 @@ -92,7 +92,7 @@ local function jump(entries)
 12
 13    -- Use the quickfix list to store remaining locations
 14    if #locations > 1 then
 15 -    vim.lsp.util.set_qflist(vim.lsp.util.locations_to_items(locations, offset_encoding))
 16 +    vim.fn.setqflist(vim.lsp.util.locations_to_items(locations, offset_encoding))
 17      vim.cmd 'copen'
 18      vim.cmd 'wincmd p'
 19    end

**Comment by ojroques** [comment]
Thanks!
