### ISSUE TITLE
latest nvim causes vim.tbl_islist is deprecated, use vim.islist instead

### ISSUE THREAD

**Issue by mckellygit** [ojroques/nvim-lspfuzzy#41]
Hi,

Thanks for awesome nvim-lspfuzzy.  Latest nvim causes this -

vim.tbl_islist is deprecated, use vim.islist instead. :help deprecated
Feature will be removed in Nvim 0.12
stack traceback:
        vim/shared.lua: in function 'tbl_islist'
        /home/user/.vim/bundle/nvim-lspfuzzy/lua/lspfuzzy.lua:169: in function 'handler'

The fix I suppose is simply -

diff --git a/lua/lspfuzzy.lua b/lua/lspfuzzy.lua

-  result = vim.tbl_islist(result) and result or {result}
+  result = vim.islist(result) and result or {result}

I can create a PR if you want.  Altho perhaps this needs a version check so it works with old and newer nvim ?

thx,
-m

**Comment by ojroques** [comment]
Thanks for reporting that, it's fixed in the latest commit :)
