### ISSUE TITLE
bad argument #1 to 'unpack' (table expected, got string)

### ISSUE THREAD

**Issue by teto** [ojroques/nvim-lspfuzzy#7]
I've updated everything and I am on neovim master but I get

```
|| E5108: Error executing lua ...to/.local/share/nvim/site/nvim-lspfuzzy/lua/lspfuzzy.lua:95: bad argument #1 to 'unpack' (table expected, got string)
|| E5108: Error executing lua ...to/.local/share/nvim/site/nvim-lspfuzzy/lua/lspfuzzy.lua:95: bad argument #1 to 'unpack' (table expected, got string)
```
on 
:LspDiagnosticAll

**Comment by ojroques** [comment]
Hello!

I'll look into it. Does that happen only for `:LspDiagnosticAll`? Are you using the [fzf_preview_window](https://github.com/junegunn/fzf.vim/blob/811b8607c653afe365bb97e6568501b0ad498017/doc/fzf-vim.txt#L179) option in your config?

**Comment by teto** [comment]
Nope it fails for LspDiagnostic too, if I comment out `let g:fzf_preview_window = 'right:30%'`, then lspfuzzy works

**Comment by ojroques** [comment]
Should work now. The plugin was expecting a table for that option. I added a check to convert a string value to a table.
