### ISSUE TITLE
Feature request: Adding support for telescope.

### ISSUE THREAD

**Issue by rafamadriz** [ojroques/nvim-lspfuzzy#9]
Is there any plans for adding the option to choose between Telescope and FZF ?

At the moment, Telescope seems to be the most extensible fuzzy finder (and in consequence, probably the best one), it is written entirely in lua (unlike the FZF plugin for vim) and it has become the most popular fuzzy finder for users moving their configuration over to lua,  and those users usually only want lua plugins. 

It just makes sense adding support for telescope. How difficult would it be to implement ? Both plugins are written in lua so maybe that would make it a little bit easier.

**Comment by ojroques** [comment]
Hi,

I think there's a misunderstanding here about the goal of this plugin. This plugin is to allow people who are happy with FZF, want to keep using it and want to use FZF to navigate the built-in LSP client results.

If you're not in this case, you should use Telescope which comes with full support for the LSP client already (unlike FZF) and you can totally ignore this plugin :)

**Comment by rafamadriz** [comment]
>  you should use Telescope which comes with full support for the LSP client already

My bad, I didn't know Telescope already has full LSP support. I was having issues with LSP when looking for references because of the way buffers  are handled, so I was looking for a better solution.

You're absolutely right, it makes no sense supporting Telescope if it already LSP builtin. 

Thanks for mentioning that, if you wouldn't have say that I'd be still looking for a solution.
